name = "slides.ihate.work"
compatibility_date = "2023-10-16"

main = "hono-server.tsx"

[site]
bucket = "./public"

[placement]
mode = "smart"

[env]
route = { pattern = "slides.ihate.work", custom_domain = true }
